#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TheGameDB.Resource", IsApplication=true)]

namespace TheGameDB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::TheGameDB.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int splash_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int splash_fade_out = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int THGDBLogo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int GameCoopText = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int GameDeveloperText = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int GameGenresText = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int GameImage = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int GameOverviewText = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int GamePlatformText = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int GamePlayersText = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int GamePublisherText = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int GameRatingText = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int GameReleaseDateText = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int GameTabSearchBarLayout = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int GameTabSearchButton = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int GameTabSearchEditText = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int GameTabSearchListView = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int GameTabSearchTableLayout = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int GameTitleText = 2131099649;
			
			// aapt resource value: 0x7f060029
			public const int GamesDBLoginImageView = 2131099689;
			
			// aapt resource value: 0x7f060025
			public const int MainProfileSearchBarButton = 2131099685;
			
			// aapt resource value: 0x7f060015
			public const int MainSearchRowPlatformTextView = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int MainSearchRowReleaseTextView = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int MainSearchRowTitleTextView = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int PlatformCPUText = 2131099676;
			
			// aapt resource value: 0x7f06001a
			public const int PlatformDeveloperText = 2131099674;
			
			// aapt resource value: 0x7f060020
			public const int PlatformDisplayText = 2131099680;
			
			// aapt resource value: 0x7f06001e
			public const int PlatformGraphicsText = 2131099678;
			
			// aapt resource value: 0x7f060016
			public const int PlatformImage = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int PlatformManufacturerText = 2131099675;
			
			// aapt resource value: 0x7f060022
			public const int PlatformMaxControllersText = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int PlatformMediaText = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int PlatformMemoryText = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int PlatformOverviewText = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int PlatformRatingText = 2131099672;
			
			// aapt resource value: 0x7f06001f
			public const int PlatformSoundText = 2131099679;
			
			// aapt resource value: 0x7f060023
			public const int PlatformTabListView = 2131099683;
			
			// aapt resource value: 0x7f060017
			public const int PlatformTitleText = 2131099671;
			
			// aapt resource value: 0x7f060026
			public const int ProfileAccountIdentifierEditText = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int ProfileChangeIdentifierButton = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int SplashScreenLayout = 2131099688;
			
			// aapt resource value: 0x7f060024
			public const int StatusBarLinearLayout = 2131099684;
			
			// aapt resource value: 0x7f060011
			public const int frameLayout = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout1 = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout3 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GameSearchTabLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainSearchRowLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlatformLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlatformTabLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ProfileLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SplashScreenLayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int facebookLogin = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
