#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.34003
=======
//     Runtime Version:4.0.30319.34014
>>>>>>> 45b14b83d14d16b2b19cbd5ef90077251dcc5a32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TheGameDB.Resource", IsApplication=true)]

namespace TheGameDB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::TheGameDB.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int THGDBLogo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int CreateAccountAddButton = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int CreateAccountIdentifierEditText = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int CreateAccountInfoTextView = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int GamesDBLoginImageView = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int LoginButton = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int btnFQLSample = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int btnGraphSample = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int btnLogin = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int btnPostWall = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int btnRemovePost = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int imgUser = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int txtvUserName = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateAccountLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int facebookLogin = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
