#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TheGameDB.Resource", IsApplication=true)]

namespace TheGameDB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int splash_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int splash_fade_out = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int THGDBLogo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002a
			public const int FavoriteMenuItem = 2131165226;
			
			// aapt resource value: 0x7f070007
			public const int GameCoopText = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int GameDeveloperText = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int GameGenresText = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int GameImage = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int GameOverviewText = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int GamePlatformText = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int GamePlayersText = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int GamePublisherText = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int GameRatingText = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int GameReleaseDateText = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int GameTabSearchBarLayout = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int GameTabSearchButton = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int GameTabSearchEditText = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int GameTabSearchListView = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int GameTabSearchTableLayout = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int GameTitleText = 2131165185;
			
			// aapt resource value: 0x7f070029
			public const int GamesDBLoginImageView = 2131165225;
			
			// aapt resource value: 0x7f07002e
			public const int HelpMenuItem = 2131165230;
			
			// aapt resource value: 0x7f070015
			public const int MainSearchRowPlatformTextView = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int MainSearchRowReleaseTextView = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int MainSearchRowTitleTextView = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int PlatformCPUText = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int PlatformDeveloperText = 2131165210;
			
			// aapt resource value: 0x7f070020
			public const int PlatformDisplayText = 2131165216;
			
			// aapt resource value: 0x7f07001e
			public const int PlatformGraphicsText = 2131165214;
			
			// aapt resource value: 0x7f070016
			public const int PlatformImage = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int PlatformManufacturerText = 2131165211;
			
			// aapt resource value: 0x7f070022
			public const int PlatformMaxControllersText = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int PlatformMediaText = 2131165217;
			
			// aapt resource value: 0x7f07001d
			public const int PlatformMemoryText = 2131165213;
			
			// aapt resource value: 0x7f070019
			public const int PlatformOverviewText = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int PlatformRatingText = 2131165208;
			
			// aapt resource value: 0x7f07001f
			public const int PlatformSoundText = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int PlatformTabListView = 2131165219;
			
			// aapt resource value: 0x7f070017
			public const int PlatformTitleText = 2131165207;
			
			// aapt resource value: 0x7f07002c
			public const int RateAppMenuItem = 2131165228;
			
			// aapt resource value: 0x7f070024
			public const int SettingAccIdInfoTextView = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int SettingsAccountIdentifierEditText = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int SettingsChangeIdentifierButton = 2131165223;
			
			// aapt resource value: 0x7f070025
			public const int SettingsCurrentAccountIdTextView = 2131165221;
			
			// aapt resource value: 0x7f07002d
			public const int SettingsMenuItem = 2131165229;
			
			// aapt resource value: 0x7f070028
			public const int SplashScreenLayout = 2131165224;
			
			// aapt resource value: 0x7f07002b
			public const int UnFavoriteMenuItem = 2131165227;
			
			// aapt resource value: 0x7f070011
			public const int frameLayout = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout1 = 2131165202;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout3 = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GameSearchTabLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainSearchRowLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlatformLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlatformTabLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SettingsLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SplashScreenLayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int ActionBarMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int favoriteText = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int helpText = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int rateAppText = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int settingsAccIdText = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int settingsText = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int unFavoriteText = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
